### ISSUE TITLE
[BUG]:  No module named 'PySide2'

### ISSUE THREAD

**Issue by dx0x58** [TrevisanGMW/gt-tools#203]
### Description of the bug

Hi! I cannot install gt-tools in Maya 2025.1; I got an error after dragging the script into the viewport.

 `# Error: ModuleNotFoundError: file D:\D_Downloads/gt-tools-3.3.1/gt-tools-3.3.1\gt\ui\progress_bar.py line 1: No module named 'PySide2'`
 
 It looks like that in Maya 2025, PySide dependency was upgraded from 2 to 6 version:
 
<img width="854" alt="image" src="https://github.com/TrevisanGMW/gt-tools/assets/3293970/8004f1e6-e8ca-4d95-96f9-7cb6f279084a">

More about it: https://help.autodesk.com/view/MAYADEV/2025/ENU/?guid=Qt6Migration

### Steps To Reproduce

1. Drag script into the viewport and check console log

**Comment by TrevisanGMW** [comment]
Hey @dx0x58, thanks for pointing that out. 
Yes, I'll need to update the way it imports PySide to make it compatible with Maya 2025. Thanks for adding all this info here 👍

**Comment by Polarcosine** [comment]
By any chance do you know when you might be able to make it compatible, I love this plugin and would love to use it with the newest version.

**Comment by TrevisanGMW** [comment]
Hey @Polarcosine thanks for showing interest.
I've been quite busy with my day job lately, but I'll likely have some time soon to work on making it compatible with the newest version. I appreciate your patience!
This might happen maybe next month or so. 👍

**Comment by TrevisanGMW** [comment]
Hey @dx0x58 and @Polarcosine, I've updated the package ([v3.4.0](https://github.com/TrevisanGMW/gt-tools/releases/tag/v3.4.0))
It's now compatible with PySide2 and PySide6, I tested it on Maya 2023, 2024, and 2025 without issues.
Due to the big pattern change, you might have to update it using the installer instead of the updater tool. Let me know if you guys run into any errors 👍
